### ISSUE TITLE
Data scientist vs ML developer

### ISSUE THREAD

**Issue by tguructa** [bhavaniravi/ama#2]
Can you help me to understand the roles of a ML Developer and a Data Scientist?
Do they have overlapping roles?

**Comment by bhavaniravi** [comment]
[You should read my favorite Quora answer for this](https://www.quora.com/What-is-difference-between-a-Data-Scientist-and-a-Machine-Learning-Engineer-Which-is-better-in-terms-of-salary-and-long-term-growth-and-why-How-are-they-correlated)
