### ISSUE TITLE
How can i be a speaker to some event ?

### ISSUE THREAD

**Issue by abhinpai** [bhavaniravi/ama#4]
I want to give speak about some future events. How can i prepare for that. What factors that i should consider and how was you first experience ?

**Comment by bhavaniravi** [comment]
I'm going to split your question into multiple issues and answer them separately

**How can I be a speaker to some event ?** 

**Levels of Speaking at Event**

1. Speaking at a local meetup group
2. Speaking at a local conference
3. Speaking at an international conference
4. Becoming a keynote speaker

**How to find the event to speak at?** 

1. Goto meetup.com find a meetup which is closer to you 
2. Reach out to the organizer by sending them a message 
3. Be explicit on what you want to talk about 

Most meetup organizers would be happy to have you as a speaker if you have a good topic in hand. 
Once you are comfortable speaking in front of audience you can start adding your talk proposal to conferences.

[How to prepare](#5)
[My First Speaking Experience](#6)
