### ISSUE TITLE
Use of GitHub 

### ISSUE THREAD

**Issue by aldrin163** [bhavaniravi/ama#7]
Hi, 
How should GitHub be used other than for collaboration. I have heard that for interviews and placements, the GitHub profile is really important. So does that mean we have to upload all our  projects to GitHub as a way of showcasing our works?

**Comment by bhavaniravi** [comment]
Yes, Yes, Yes, Every piece of code you write can go into GitHub. This comes in handy when you give interviews and lookout for great opportunities.

But make sure not to push code you are not confident about, or code that is not well documented. 

Make sure all the repos have a clear readme file with setup instructions, maybe a video of demo or link to the demo
